language: rust
rust:
  - nightly
  - stable
#cache: cargo

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0b69c3f09cd78b94d40d
    on_success: change
    on_failure: always
    on_start: never

script:
  - cargo test --all
  - cargo bench
