[package]
name = "froggy"
version = "0.2.0"
authors = ["Dzmitry Malyshau <kvarkus@gmail.com>",
           "Ilya Bogdanov <fumlead@gmail.com>"]
documentation = "https://docs.rs/froggy/"
repository = "https://github.com/kvark/froggy"
keywords = ["gamedev", "ecs"]
license = "Apache-2.0"
exclude = ["doc", ".travis.yml"]
description = """
Froggy is a prototype for the Component Graph System programming model. It aims to combine the convenience of composition-style Object-Oriented Programming with the performance close to Entity-Component Systems.
"""
build = "build.rs"

[workspace]
members = ["demos/cubes"]

[dependencies]

[build-dependencies]
skeptic = "0.9"

[dev-dependencies]
skeptic = "0.9"

[features]
default = ["inline"]
inline = []